#ifndef COMMON_ERROR_H
#define COMMON_ERROR_H

#define ERROR_SERVER_DOMAIN_SOCKET_CREATE 1001
#define ERROR_SERVER_BIND_DOMAIN_SOCKET   1002
#define ERROR_SERVER_LISTEN_CONNECTION    1003
#define ERROR_SERVER_EPOLL_FD_CREATE      1004
#define ERROR_SERVER_EPOLL_CTL            1005
#define ERROR_SERVER_EPOLL_WAIT           1006
#endif