#ifndef COMMON_ERROR_H
#define COMMON_ERROR_H

#define ERROR_SERVER_DOMAIN_SOCKET_CREATE 1001
#define ERROR_SERVER_BIND_DOMAIN_SOCKET   1002
#define ERROR_SERVER_LISTEN_CONNECTION    1003
#define ERROR_SERVER_EPOLL_FD_CREATE      1004
#define ERROR_SERVER_EPOLL_CTL            1005
#define ERROR_SERVER_EPOLL_WAIT           1006
#define ERROR_SERVER_INVALID_INPUT        1007
#define ERROR_SERVER_CLIENT_EXIT          1008
#define ERROR_SERVER_RECV_FD              1009
#define ERROR_SERVER_SEND_FD              1010


#define ERROR_CLIENT_EPOLL_CTL            2001
#define ERROR_CLIENT_READ_STDIN           2002
#define ERROR_CLIENT_DATA_SOCKET_CREATE   2003


#endif